### ISSUE TITLE
Linux下使用Makefile编译时，提示“Utility/global_linux.h: No such file or directory”

### ISSUE THREAD

**Issue by lizhengnacl** [NLPIR-team/NLPIR#8]
环境： CentOS 7 64位

下载包版本：[NLPIR/ICTCLAS2016分词系统下载包](http://ictclas.nlpir.org/upload/20160304111057_ICTCLAS2016%E5%88%86%E8%AF%8D%E7%B3%BB%E7%BB%9F%E4%B8%8B%E8%BD%BD%E5%8C%85.zip)

使用Makefile编译文件时，提示如下错误：
```
Example-C.cpp:675:40: fatal error: ../../Utility/global_linux.h: No such file or directory
#include "../../Utility/global_linux.h"
```
下载包中中并未出现<code>global_linux.h</code>

这个问题应该如何修复呢？

打扰您了。

**Comment by Dr-Kevin-Zhang** [comment]
麻烦使用这个例子程序：
https://github.com/NLPIR-team/NLPIR/blob/master/NLPIR%20SDK/NLPIR-ICTCLAS/projects/ICTCLAS_C%2B%2B/main.cpp 




Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts
 
发件人： lizhengnacl
发送时间： 2016-03-15 20:25
收件人： NLPIR-team/NLPIR
主题： [NLPIR] Linux下使用Makefile编译时，提示“Utility/global_linux.h: No such file or directory” (#8)
环境： CentOS 7 64位
下载包版本：NLPIR/ICTCLAS2016分词系统下载包
使用Makefile编译文件时，提示如下错误：
Example-C.cpp:675:40: fatal error: ../../Utility/global_linux.h: No such file or directory
#include "../../Utility/global_linux.h"

下载包中中并未出现global_linux.h
这个问题应该如何修复呢？
打扰您了。
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/NLPIR-team/NLPIR/issues/8

**Comment by lizhengnacl** [comment]
@Dr-Kevin-Zhang 谢谢，麻烦您了
